[package]
name = "libellule"
description = "Unofficial implementation of the PRONOTE protocol"
readme = "README.md"
keywords = ["pronote", "client", "api"]
categories = ["api-bindings", "authentication"]
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
aes = "0.9.1"
base64 = "0.23.1"
cbc = { version = "0.2.1", features = ["alloc"] }
hex = "0.4.3"
md5 = "0.8.1"
rand = "0.10.2"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3.21.0"
sha2 = "0.11.0"
serde_repr = "0.1.21"
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting", "macros", "parsing"] }
tokio = { workspace = true, features = ["sync"] }
url = { workspace = true }

[lints.rust]
missing_docs = "warn"
unsafe_code = "deny"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
