[package]
name = "libellule-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
inquire = { version = "0.9.4", features = ["date"] }
libellule = { version = "0.1.1", path = "../libellule" }
time = { version = "0.3.55", features = ["macros"] }
tokio = { version = "1.53.0", features = ["full"] }
url = "2.5.8"
