mod authentication;
mod function;
mod grades;
mod homework;
mod identification;
mod menu;
mod parameters;
mod reference;
mod timetable;
mod value;

pub use authentication::*;
pub use function::*;
pub use grades::*;
pub use homework::*;
pub use identification::*;
pub use menu::*;
pub use parameters::*;
pub use reference::*;
pub use timetable::*;
pub(crate) use value::*;
