mod authentication;
mod function;
mod grades;
mod homework;
mod identification;
mod menu;
mod parameters;
mod reference;
mod timetable;
mod value;

pub(crate) use authentication::*;
pub(crate) use function::*;
pub(crate) use grades::*;
pub(crate) use homework::*;
pub(crate) use identification::*;
pub(crate) use menu::*;
pub(crate) use parameters::*;
pub(crate) use reference::*;
pub(crate) use timetable::*;
pub(crate) use value::*;
