[package]
name = "libellule-uniffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib", "staticlib"]
name = "libellule"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
libellule = { path = "../libellule" }
thiserror = "2.0.18"
time = "0.3.55"
tokio = { version = "1.53.0", features = ["full"] }
uniffi = { version = "0.31.1", features = ["cli", "tokio"] }
url = "2.5.8"

[build-dependencies]
uniffi = { version = "0.31.1", features = ["build"] }
