[package]
name = "libellule-uniffi"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[lib]
crate-type = ["lib", "staticlib"]
name = "libellule"

[dependencies]
libellule = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting", "macros", "parsing"] }
uniffi = { workspace = true, features = ["tokio"] }
