[package]
name = "libellule-uniffi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lib]
name = "libellule"
crate-type = ["lib", "staticlib"]

[dependencies]
libellule = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting", "macros", "parsing"] }
uniffi = { workspace = true, features = ["tokio"] }
