name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: ${{ matrix.crate }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        crate:
          - libellule
          - libellule-uniffi

    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - run: cargo fmt -p ${{ matrix.crate }} --check
      - run: cargo clippy -p ${{ matrix.crate }} --all-targets --all-features --keep-going -D warnings
      - run: cargo build -p ${{ matrix.crate }} --all-targets --all-features
      - run: cargo test -p ${{ matrix.crate }} --all-targets --all-features
